# -*- coding: utf-8 -*-
"""notebook422f07dc5d

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/ferroudjabtlb/notebook422f07dc5d.e41f0044-ecc1-479c-a5b7-fedb4d9ff16d.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251121/auto/storage/goog4_request%26X-Goog-Date%3D20251121T135558Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D425a94562d2ba39507609679aa2b9cdaa41bb0d0204ddb71aa721fff5609e3979e993413d01e8ba71660e785155f88aceb00c2f7a5409a96f19691d86b76c4a1e49a45c0741e47335072e089b31c26b317401342b0e5d367a5a1ae634427bdd3fb9bc39a21195de946043ee71b72d61cd8170cf3bda5cf9edbf5191e7c7c5f61272b15bbaa3e933e42c52bd671f3f84bf687f1f88508f35b476c4aa34e0f01ef06a194db62c9b2b295b74eacda00d8c8efd9a91ed7390796b26319d3a11e9d8d72ef71a2162686095e5888d80e7f6b2271a4ae99363690e411b4508688892ad34ce6a8cc30bed9de8582c89b76153d897a41c9f08484d12976731fdd970a5a45
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

home_data_for_ml_course_path = kagglehub.competition_download('home-data-for-ml-course')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

"""Resume de tout  """

X = pd.read_csv("/kaggle/input/home-data-for-ml-course/train.csv")
X_test = pd.read_csv("/kaggle/input/home-data-for-ml-course/test.csv")
X.describe()

X.dropna(axis=0, subset=['SalePrice'], inplace=True)
y = X.SalePrice
X.drop(['SalePrice'], axis=1, inplace=True)

#Split Method
from sklearn.model_selection import train_test_split

X_train_f, X_valid_f, y_train_f, y_valid_f = train_test_split(X,y, train_size=0.8, test_size=0.2,
                                                                random_state=0)

#col cat and num col

cat_cols = [i for i in X_train_f.columns if X_train_f[i].nunique()<10
            and X_train_f[i].dtypes == "object"]

num_cols = [i for i in X_train_f.columns if X_train_f[i].dtypes == "int64, float64"]

my_cols = cat_cols + num_cols

X_train = X_train_f[my_cols].copy()
X_valid = X_valid_f[my_cols].copy()
X_test_ = X_test[my_cols].copy()

#method 1 : Encoding with OHE and preprocessing with a pipeline

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

numerical_tranformers = SimpleImputer(strategy='constant')
categorical_tranformers = Pipeline(steps=[('imputer', SimpleImputer(strategy = 'most_frequent')),
                     ('onehot', OneHotEncoder(handle_unknown = 'ignore'))])

from sklearn.compose import ColumnTransformer
preprocessor = ColumnTransformer(transformers=[('numeric', numerical_tranformers, num_cols),
                                            ('category', categorical_tranformers, cat_cols)])

#method 2 : Encoding with OHE and preprocess without using a pipeline

OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(X_train[my_cols]))
OH_cols_valid = pd.DataFrame(OH_encoder.transform(X_valid[my_cols]))

# Method 3 : One-hot encode the data (to shorten the code, we use pandas)
X_train = pd.get_dummies(X_train)
X_valid = pd.get_dummies(X_valid)
X_test = pd.get_dummies(X_test)
X_train, X_valid = X_train.align(X_valid, join='left', axis=1)
X_train, X_test = X_train.align(X_test, join='left', axis=1)

#build the model
from xgboost import XGBRegressor

my_model = XGBRegressor(random_state=0)
my_model.fit(X_train, y_train_f)

pred = my_model.predict(X_valid)

mae_err = mean_absolute_error(pred, y_valid_f)













































