# -*- coding: utf-8 -*-
"""notebook4cb72877e3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/ferroudjabtlb/notebook4cb72877e3.d83807a3-81b7-42c3-baba-2618955bfa0d.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251112/auto/storage/goog4_request%26X-Goog-Date%3D20251112T112344Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D64849a672ad3cb8032ddfeb402c640f0804b7b7ace046063b7baae57ff05ff4720b056f8e9d8d94f48fda9337369919da96c6843d26bbdacfa6ada09c390170499facefedae199d6a1ec0f8a4bf632d5d6cf25dccdf4495efea9809827cb4b31d982cfdf67b78d1a9d42a4aba9250c41cd39e5f0e61e31dae98723030d252ff7813fc858acea74f5e2dc8f46ad622a47f6e08eddcfc71d05ae879b31d2c039edd55b3c3d1588ec16d89c09ebdf74da93da14f2bdec2797346902fe784d6ea378219b441ba81f6589240f1583e28a90592f15bf58a243a4f301173c9cca94f26430189d280010abb7d8a0c2b98ce52e587bee7537eddb95ea9f5d3c2643d58dde
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
uciml_pima_indians_diabetes_database_path = kagglehub.dataset_download('uciml/pima-indians-diabetes-database')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

X_train_data = pd.read_csv("/kaggle/input/pima-indians-diabetes-database/diabetes.csv")
X_train_data.describe()

"""SETUP"""

X_train_data.dropna(axis=0, subset=['Outcome'], inplace=True)
y = X_train_data.Outcome
X_train_data.drop(['Outcome'], axis=1, inplace=True)


"""Preprocessing"""

cat_col = [i for i in X_train_data.columns if X_train_data[i].nunique() < 10
          and X_train_split[i].dtypes == 'object']

num_col = [i for i in X_train_data.columns if X_train_data[i].dtypes in ['int64', 'float64']]

my_col = cat_col + num_col

X_train = X_train_data[my_col].copy()
X_valid = X_train_data[my_col].copy()


"""Model Fit"""

from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

def get_scores(n_estimators):
    my_pipeline = Pipeline(steps=[('preprocessor', SimpleImputer()),
                              ('model', RandomForestClassifier(n_estimators, max_depth = 10, random_state=0))])
    scores = cross_val_score(my_pipeline, X_train, y, cv=5, scoring='accuracy')

    return scores

tree_values = [50, 100, 150, 200, 250, 300, 350, 400]
result={}

for i in tree_values:
    result[i] = get_scores(i)

#View the results
for n, scores in result.items():
    print(f"{n} Tree → Mean = {scores.mean():.3f}, Standard deviation = {scores.std():.3f}")


"""Predictions"""

#Find the best number of tree estimators
n_estimators_best = max(result, key=lambda k: result[k].mean())
print("\n The best number of tree is :", n_estimators_best)
print(f" Mean Score : {result[n_estimators_best].mean():.3f}")

output = pd.DataFrame({'Age': X_train.Age, 'Outcome': y})
output.to_csv('Test_Pima_Indians_Diabetes.csv', index=False)

print("Number of non-diabetic person is :", y.value_counts()[0])
print("Number of diabetic person is :", y.value_counts()[1])
