# -*- coding: utf-8 -*-
"""notebook91b78e85df

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/ferroudjabtlb/notebook91b78e85df.62eacfc3-6e04-45ac-b7ea-764ddcc780ba.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251107/auto/storage/goog4_request%26X-Goog-Date%3D20251107T154200Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D4c60a28b1885e62547df9d7f2fa355442c85dfe76964ac16fa65780091090ab92e3f3c818c0b6015c5278d8fee400d0117dca850a57b52bd2d0ad0dc5f4f2fb8756f75e7c57db8fb951a8998401796572152f6c9f6e3bef3aae975db1ba387ce89e99080d5b90ad29730fa07cb8333b82916eeaf27899690519ae5e82137b3890d018656ed5aa3789c30eb08a6263a9f986e31e32bd268883bdc665ee3b63c081d9addc8588cd79dacab08a1add9b8f65cdccadabab1e12409bb8e9e0a2beb10712388bc399768bdac991cc7e7f6b29d90c3fffee58e0e794b396254ad91ea1f9e3e2f23fe5e043d9d2575128920af51e54f313f7116bb61361582bd5d9fed6b
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

titanic_path = kagglehub.competition_download('titanic')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

"""**The competition is simple: use machine learning to create a model that predicts which passengers survived the Titanic shipwreck. In this challenge, we ask you to build a predictive model that answers the question:**

- **“what sorts of people were more likely to survive?” using passenger data (ie name, age, gender, socio-economic class, etc).**


    - Train.csv will contain the details of a subset of the passengers on board (891 to be exact) and importantly, will reveal whether they survived or not, also known as the “ground truth”.

    - Test.csv dataset contains similar information but does not disclose the “ground truth” for each passenger. It’s your job to predict these outcomes.

    - Using the patterns you find in the train.csv data, predict whether the other 418 passengers on board (found in test.csv) survived.

"""

#Read the data

X_train_full = pd.read_csv("/kaggle/input/titanic/train.csv")
X_test_full = pd.read_csv("/kaggle/input/titanic/test.csv")

print("Setup Complete")

#View the data
X_train_full.describe()

#Step 1 : Setup Data

#1 - Cleaning
X_train_full.dropna(axis=0, subset=['Survived'], inplace=True)
y = X_train_full.Survived
X_train_full.drop(['Survived'], axis=1, inplace=True)
#X_train_full.describe() #Check

#2 - Split on the dataset
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y, random_state=0)

"""**- PREPROCESSING STEP**"""

#Step 2 : Identify cardinality of categorical columns and numerical columns

cardinality = X_train.select_dtypes(include=['object']).nunique()
#print(cardinality)

categorical_cols = [i for i in X_train.columns if X_train[i].nunique()<10
                    and X_train[i].dtypes == 'object']

numerical_cols = [i for i in X_train.columns if X_train[i].dtypes in ['int64', 'float64']]

#Step 3 : Assembling and viewing the informations that will been used by our model
my_cols = categorical_cols + numerical_cols
#print(my_cols)

#Update Data with cardinality
X_train_ = X_train[my_cols].copy()
X_valid_ = X_valid[my_cols].copy()
X_test_ = X_test_full[my_cols].copy()

#Step 4 : Encode categorical column and numerical column
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

categorical_transformers = Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                                           ('onehot', OneHotEncoder(handle_unknown = 'ignore'))])

numerical_transformers = Pipeline(steps=[('imputer', SimpleImputer(strategy='constant'))])

preprocessing = ColumnTransformer(transformers=[('numeric', numerical_transformers, numerical_cols),
                                                ('category',categorical_transformers, categorical_cols)])

"""**- FITTING MODEL**"""

from sklearn.ensemble import RandomForestRegressor

my_model = RandomForestRegressor(n_estimators = 100, random_state = 0)

my_pipeline = Pipeline(steps=[('preprocessor', preprocessing), ('model', my_model)])

my_pipeline.fit(X_train_, y_train)


"""**- Predictions**"""

predictions = my_pipeline.predict(X_valid_)

#MAE
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(predictions, y_valid)

print("The MAE score is : ", mae)


#Precition on the "test" data set

predictions_test = my_pipeline.predict(X_test_)
print("The prediction give : ", predictions_test)


#Save test pred to file

output = pd.DataFrame({'Id': X_test_.index, 'Survived': predictions_test})
output.to_csv('Test_ML_Titanic_disaster.csv', index=False)
